dataset_path: Framework/eventLogs
trace_ids_path: Framework/traceIDs

win_size: 500
sub_window_num: 6
min_subwindows: 4
max_subwindows: 6
slide_sub_windows: 1
cooldown_windows: 12

hidden_size: 16
output_size: 8
learning_rate: 0.001
epochs: 10

m: 10
k: 10

eps_small: 0.01
eps_big: 0.1

temperature: 0.5
lamb: 0.1
windows_per_threshold_update: 2
percentile: 0.9
consecutive_required: 2